### ISSUE TITLE
サーバーへのJSONデータ送信について

### ISSUE THREAD

**Issue by moririnUs** [hamuchan214/CN2024morigaki#29]
ログイン、ログオンの際に送信したデータを、サーバー側でうまく受信できていないらしい。
恐らくclient.pyに問題あり。

**Comment by hamuchan214** [comment]
該当のバグはソケット接続時に空のデータを送信していることで発生してるものです。
https://github.com/hamuchan214/CN2024morigaki/commit/2d663b1d5b0bf2b80ac7ac793df86e0532a96fd6
上記PRにして修正済み

**Comment by hamuchan214** [comment]
修正済みのためクローズ
